//
// Created by pollini on 01/02/2022.
//

#ifndef RL_DA_ZERO_SRC_ENTITY_COMPONENTS_TAGS_H
#define RL_DA_ZERO_SRC_ENTITY_COMPONENTS_TAGS_H

struct HeroTag {};

#endif  // RL_DA_ZERO_SRC_ENTITY_COMPONENTS_TAGS_H
